name: GitHub Metrics Generation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate-metrics:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      # 2. Configure Git identity
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 3. Sync latest code
      - name: Synchronize repository
        run: |
          git pull --rebase origin main
          git fetch --prune

      # 4. Create output directory
      - name: Create assert directory
        run: mkdir -p assert

      # 5. Generate charts
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
          
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Metrics generation
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.NICK_2025 }}
          user: ${{ github.repository_owner }}
          filename: assert/github-metrics.svg
          plugins: stars,activity,repositories,followers,languages,traffic

     
      # 6. 移动所有SVG到assert目录
      - name: Move SVG files to assert
        run: |
          mv *.svg assert/
      # 7. 检查文件变化
      - name: Check for changes
        id: changes
        run: |
          git add assert/*.svg

      # 8. 提交变更
      - name: Commit and push changes
        if: steps.changes.outputs.has_changes == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📊 Auto-update metrics [skip ci]"
          branch: main
          file_pattern: assert/*.svg
          force: true
          skip_fetch: true
