name: GitHub Metrics Generation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate-metrics:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      # 2. Configure Git identity
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 3. Sync latest code
      - name: Synchronize repository
        run: |
          git pull --rebase origin main
          git fetch --prune

      # 4. Create output directory
      - name: Create assert directory
        run: mkdir -p assert

      # 5. Generate charts
      # Light theme snake
      - name: Generate light snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: 
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.NICK_2025 }}

      # Metrics generation
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.NICK_2025 }}
          user: ${{ github.repository_owner }}
          filename: assert/github-metrics.svg
          plugins: stars,activity,repositories,followers,languages,traffic

     
      # 6. 移动所有SVG到assert目录
      - name: Move SVG files to assert
        run: |
          mv *.svg assert/
      # 7. 检查文件变化
      - name: Check for changes
        id: changes
        run: |
          git add assert/*.svg

      # 8. 提交变更
      - name: Commit and push changes
        if: steps.changes.outputs.has_changes == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📊 Auto-update metrics [skip ci]"
          branch: main
          file_pattern: assert/*.svg
          force: true
          skip_fetch: true
