# This is a basic workflow to help you get started with Actions

name: CI2

# Controls when the workflow will run
on:
  schedule: # UTC 0:00 Beijing 8:00 (北京时间0点自动更新一次)
    - cron: "5 0 * * *"
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Metrics generation
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.NICK_2025 }}
          user: ${{ github.repository_owner }}
          filename: assert/github-metrics.svg
          plugins: stars,activity,repositories,followers,languages,traffic
