name: Sync Output Files

on:
  schedule:
    # UTC 0:20 (北京时间 8:20)
    - cron: "20 0 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main  # 明确检出 main 分支

      - name: Sync Files from Output Branch
        run: |
          # 从 output 分支恢复 assert/ 目录内容
          git fetch --all
          gitcheckout main
          git checkout output -- assert/

      - name: Check for Changes
        id: check-changes
        run: |
          # 检测是否有文件变更
          git add -A assert/
          if git diff-index --quiet HEAD --; then
            echo "No changes detected."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit & Push Changes
        if: steps.check-changes.outputs.has_changes == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🔄 Sync Output Files [skip ci]"
          branch: main
          file_pattern: assert/*
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
