name:end build

on:
  schedule: # UTC 0:00 Beijing 8:00 (北京时间0点自动更新一次)
    - cron: "20 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
