name:end build

on:
  schedule: # UTC 0:00 Beijing 8:00 (北京时间0点自动更新一次)
    - cron: "20 0 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge dev into main
        run: |
          git checkout main
          git checkout output -- / assert
          git pull origin main
